name: Country App CI/CD

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Or your preferred runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or your desired Node.js version

      - name: Install frontend dependencies
        working-directory:./frontend
        run: npm install

      - name: Run frontend tests
        working-directory:./frontend
        run: npm test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Or your desired Python version

      - name: Install backend dependencies
        working-directory:./backend
        run: pip install -r requirements.txt

      - name: Run backend tests
        working-directory:./backend
        run: pytest

      - name: Build frontend
        working-directory:./frontend
        run: npm run build

      - name: Package backend
        working-directory:./backend
        run: zip -r backend.zip.

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifacts
          path: |
          ./frontend/build
          ./backend/backend.zi